version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://anhtu:GvAo5C99PGnbdbYL@cluster0.60ue1.mongodb.net/
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
